#
#    Book Store
#

version: '3'

services:

  #############################################################################
  # Users Service
  #############################################################################
  uapp:
    image: "uapp:latest"
    depends_on:
      - db
    container_name: uapp
    restart: always
    environment:
      - PORT=8080
      - DBHOST=db
      - DBUSER=postgres
      - DBPASSWORD=admin
      - DBNAME=users
      - DBPORT=5432
      - DBSSLMODE=disable
    ports:
      - "8080:8080"

  #############################################################################
  # Books Service
  #############################################################################
  bapp:
    image: "bapp:latest"
    depends_on:
      - db
    container_name: bapp
    restart: always
    environment:
      - PORT=8081
      - DBHOST=db
      - DBUSER=postgres
      - DBPASSWORD=admin
      - DBNAME=books
      - DBPORT=5432
      - DBSSLMODE=disable
      - USER_APP_PORT=8080
    ports:
      - "8081:8081"

  #############################################################################
  # DB
  #############################################################################
  db:
    image: "postgres:latest"
    container_name: db
    restart: always
    environment:
      - POSTGRES_MULTIPLE_DATABASES=users,books
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"