#
#    Book Store
#

version: '3'

services:

  #############################################################################
  # Users Service
  #############################################################################
  uapp:
    image: "uapp:latest"
    depends_on:
      - db
    container_name: uapp
    restart: always
    environment:
      - UAPP_PORT=${UAPP_PORT}
      - UAPP_DBNAME=${UAPP_DBNAME}
      - DBHOST=${DBHOST}
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}      
      - DBPORT=${DBPORT}
      - DBSSLMODE=${DBSSLMODE}
    ports:
      - "8080:8080"

  #############################################################################
  # Books Service
  #############################################################################
  bapp:
    image: "bapp:latest"
    depends_on:
      - db
    container_name: bapp
    restart: always
    environment:
      - BAPP_PORT=${BAPP_PORT}
      - BAPP_DBNAME=${BAPP_DBNAME}
      - DBHOST=${DBHOST}
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}      
      - DBPORT=${DBPORT}
      - DBSSLMODE=${DBSSLMODE}
      - UAPP_HOST=${UAPP_HOST}
      - UAPP_PORT=${UAPP_PORT}
    ports:
      - "8081:8081"

  #############################################################################
  # DB
  #############################################################################
  db:
    image: "postgres:latest"
    container_name: db
    restart: always
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${DATABASES}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  #############################################################################
  # DB GUI - PGAdmin 4
  #############################################################################
  dbui:
    image: "dpage/pgadmin4:latest"
    container_name: dbui
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8083:80"